title: twelfthlane.net -12th-ln-&gt;
permalink: /:year/:month/:day/:title
url: http://twelfthlane.net
contact-links:
  skype: live:sashasyedin
  telegram: sashasyedin
  email: sashasyedin@outlook.com
exclude:
  - README.md
  - CNAME
plugins:
  - jemoji